rot 13

diff --git a/0x03-shell_variables_expansions/101-rot13 b/0x03-shell_variables_expansions/101-rot13
--- a/0x03-shell_variables_expansions/101-rot13
+++ b/0x03-shell_variables_expansions/101-rot13
@@ -1,2 +1,2 @@
 #!/bin/bash
-tr `echo {a..z} | tr -d ' '` `echo {n..z} $(echo {a..m} | tr -d ' '` | tr `echo {A..Z} | tr -d ' '` `echo {N..Z} $(echo {A..M}) | tr -d ' '`
+echo "$2" | tr 'A-Za-z' 'N-ZA-Mn-za-m' 2>/dev/null || echo "Invalid command. Usage: $0 encode 'text' or $0 decode 'text'"
